project_id = "iadowggdutivqopthbua"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.hard-delete-user]
verify_jwt = true

[functions.list-unassigned-users]
verify_jwt = true